plartoo/others

data_architect_misc/data_transformer/configs/AED_Kenya/config.json, data_architect_misc/data_transformer/qa_functions/common_post_transform_qa_functions.py
Hi Plartoo
Could you please merge these changes on the original repository?
These are the notes:
It was modified the common post transform qa since the list index is not taking the values for values with no decimals and the config json was modified for the new raw file
Thank you!!
=> Kenya Data Transform for April 2020 data

data_architect_misc/data_transformer/configs/Budget_Rollup/step2_generate_aggregated_budget_data.json, data_architect_misc/data_transformer/constants/budget_rollup_constants.py, data_architect_misc/data_transformer/transform_functions/wvm_budget_rollup_aggregate_functions.py
Hi Phyo
I finish Category investment trend code, Please check and let me know your comments.
=> Budget roll up

data_architect_misc/data_transformer/constants/comp_harm_constants.py
Hi Plartoo
Could you please add this change to the original code?
Please let me know if you have any comments
=> Ukraine new modification - 20200618

data_architect_misc/data_transformer/configs/AED_South_Africa/config.json, data_architect_misc/data_transformer/transform_functions/aed_south_africa_transform_functions.py
Hi Plartoo,
Could you please check my changes for this country?
=> South Africa Data Transform for April 2020 data

data_architect_misc/data_transformer/configs/AED_Kazakhstan/config.json
Hi Plartoo
Could you please check this new pull request for Kazakhstan? they were some little changes, for example, the name of the input file and the output file, and the number of columns that are going to receive from now on
=> Kazakhstan Data Transform for May 2020

data_architect_misc/data_transformer/configs/AED_GCC/config.json
Hi Plartoo,
Could you please integrate this new file with the original project?
=> GCC Data Transform for May 2020

data_architect_misc/data_transformer/configs/AED_Turkey/config.json
Hi Plartoo
Could you please review these new changes?
=> Turkey Data Transform for May 2020

data_architect_misc/data_transformer/configs/APAC_Philippines/step1_transform_raw_investment_data.json, data_architect_misc/data_transformer/configs/APAC_Philippines/step2_combine_tranformed_noncompete_and_compete_data.json, data_architect_misc/data_transformer/constants/comp_harm_constants.py, data_architect_misc/data_transformer/transform_functions/apac_philippines_transform_functions.py
Updated to use philippines specific mapping for veterinary products. But Phyo needs to help me use raw subcategory column to update values in Harmonized Category column.
=> New changes for Philippines

data_architect_misc/data_transformer/configs/LATAM_El_Salvador/config.json, data_architect_misc/data_transformer/configs/LATAM_Honduras/config.json, data_architect_misc/data_transformer/configs/LATAM_Nicaragua/config.json, data_architect_misc/data_transformer/constants/comp_harm_constants.py, data_architect_misc/data_transformer/transform_functions/common_comp_harm_transform_functions.py, data_architect_misc/data_transformer/transform_functions/common_transform_functions.py, data_architect_misc/data_transformer/transform_functions/latam_el_salvador_transform_functions.py, data_architect_misc/data_transformer/transform_functions/latam_honduras_transform_functions.py, data_architect_misc/data_transformer/transform_functions/latam_nicaragua_transform_functions.py
Hi Plartoo
Can you please help me review these changes 
Thanks!!
=> Turkey 2020 08 11

data_architect_misc/data_transformer/configs/LATAM_El_Salvador/config.json, data_architect_misc/data_transformer/configs/LATAM_Honduras/config.json, data_architect_misc/data_transformer/configs/LATAM_Nicaragua/config.json, data_architect_misc/data_transformer/constants/comp_harm_constants.py, data_architect_misc/data_transformer/transform_functions/common_comp_harm_transform_functions.py, data_architect_misc/data_transformer/transform_functions/common_transform_functions.py, data_architect_misc/data_transformer/transform_functions/latam_el_salvador_transform_functions.py, data_architect_misc/data_transformer/transform_functions/latam_honduras_transform_functions.py, data_architect_misc/data_transformer/transform_functions/latam_nicaragua_transform_functions.py
Hi Plartoo
First of all, I would like to tell you that I cannot do good commits because my git tool wouldn't want to work correctly.
but the changes that I did were:
Create the python files for Nicaragua, Honduras, and Salvador
Create the configs files for these countries
Modify some function related to the Investment values since some of them didn't work on the number of decimals already configured
Modify the function "create a file with several CSV files" contemplating as source a folder name
Modify the constant harmonization since there is a new compete advertiser
Please let me know if you have any comments or suggestions
=> Latam Central America countries Pull request

data_architect_misc/data_transformer/configs/AED_Russia/config.json, data_architect_misc/data_transformer/configs/AED_Turkey/config.json, data_architect_misc/data_transformer/transform_functions/aed_russia_transform_functions.py
Hi Plartoo,
Could you please help me to merge these changes? I did only a bit change at all of them
Thank you
=> Russia turkey 20200818

data_architect_misc/data_transformer/configs/AED_GCC/config.json
Hi Plartoo
Could you please help me checking these changes, I only updated some columns due to the new structure for GCC?
=> GCC config file

data_architect_misc/data_transformer/configs/LATAM_Mexico/step1_transform_tv_investment_data.json, data_architect_misc/data_transformer/configs/LATAM_Mexico/step2_transform_nontv_investment_data.json, data_architect_misc/data_transformer/configs/LATAM_Mexico/step3_combine_tranformed_noncompete_and_compete_data.json, data_architect_misc/data_transformer/qa_functions/common_comp_harm_qa_functions.py, data_architect_misc/data_transformer/transform_functions/latam_mexico_transform_functions.py
Hi Plartoo
Could you please check the new changes for Mexico?
Have a good day!!
=> Mexico - updated Transform module 

data_architect_misc/data_transformer/configs/LATAM_Panama/config.json, data_architect_misc/data_transformer/constants/comp_harm_constants.py, data_architect_misc/data_transformer/transform_functions/latam_panama_transform_functions.py
Hi Plartoo
Could you please check these new changes?
=> Panama - New transform module

data_architect_misc/data_transformer/configs/LATAM_Chile/config.json, data_architect_misc/data_transformer/configs/_QA/common_comp_harm_post_transform_qa_config.json, data_architect_misc/data_transformer/transform_functions/common_transform_functions.py, data_architect_misc/data_transformer/transform_functions/latam_chile_transform_functions.py
Hi Plartoo
Could you please help me with these new changes?
Thank you
=> New standarized

data_architect_misc/data_transformer/configs/APAC_Taiwan/step1_transform_raw_investment_data.json, data_architect_misc/data_transformer/configs/APAC_Taiwan/step2_transform_sos_raw_investment_data.json, data_architect_misc/data_transformer/configs/APAC_Thailand/step1_transform_raw_investment_data.json, data_architect_misc/data_transformer/configs/APAC_Thailand/step2_transform_sos_raw_investment_data.json, data_architect_misc/data_transformer/configs/LATAM_Argentina/config.json, data_architect_misc/data_transformer/transform_functions/apac_thailand_transform_functions.py, data_architect_misc/data_transformer/transform_functions/common_comp_harm_transform_functions.py, data_architect_misc/data_transformer/transform_functions/common_transform_functions.py, data_architect_misc/data_transformer/transform_functions/latam_argentina_transform_functions.py
Hi Plartoo,
Could you please help me checking these new changes?
=> New transform module - Argentina data

data_architect_misc/data_transformer/configs/LATAM_Dominican_Republic/config.json, data_architect_misc/data_transformer/transform_functions/latam_dominican_republic_transform_functions.py
Hi Plartoo,
Could you please check this new transform module?
=> Dominican - Transform module

data_architect_misc/data_transformer/configs/NA_United_States/step1_transform_raw_nontv_investment_data.json, data_architect_misc/data_transformer/configs/NA_United_States/step2_transform_raw_tv_investment_data.json, data_architect_misc/data_transformer/configs/NA_United_States/step3_transform_raw_byindustry_investment_data.json, data_architect_misc/data_transformer/configs/NA_United_States/step4_combine_tranformed_data.json, data_architect_misc/data_transformer/configs/_QA/common_comp_harm_post_transform_qa_config.json, data_architect_misc/data_transformer/constants/comp_harm_constants.py, data_architect_misc/data_transformer/transform_functions/common_transform_functions.py, data_architect_misc/data_transformer/transform_functions/na_united_states_transform_functions.py
Hi Plartoo,
Could you please hel me checking this new transform module with their correspondings changes?
My apologies for taking a lot of time to create this transform module but the data is really big and they need to use a lot time to be processed
=> Usa - Transform module

data_architect_misc/data_transformer/configs/NA_United_States/step1_transform_raw_nontv_investment_data.json, data_architect_misc/data_transformer/configs/NA_United_States/step2_transform_raw_tv_investment_data.json, data_architect_misc/data_transformer/configs/NA_United_States/step3_transform_raw_byindustry_investment_data.json, data_architect_misc/data_transformer/constants/comp_harm_constants.py, data_architect_misc/data_transformer/transform_functions/na_united_states_transform_functions.py
Hi PLartoo
Could you please help me checking these changes related to the USA data?
Thank you
=> Usa 20201201

data_architect_misc/data_transformer/transform_functions/eu_italy_transform_functions.py
Hi Plartoo
Could you please help me checking these changes?
=> Modified the function to unpivot the data with Plartoo's help - Italy

data_architect_misc/data_transformer/configs/EU_Czech_Republic/config.json, data_architect_misc/data_transformer/transform_functions/eu_czech_republic_transform_functions.py
Hi Plartoo
Could you please help me checking this new transform module?
=> Czech republic

data_architect_misc/data_transformer/configs/EU_Latvia/config.json, data_architect_misc/data_transformer/transform_functions/eu_latvia_transform_functions.py
Hi Plartoo
Could you please help me checking this new transform odule?
=> New transform module for Latvia data

data_architect_misc/data_transformer/configs/EU_Netherlands/config.json, data_architect_misc/data_transformer/constants/comp_harm_constants.py, data_architect_misc/data_transformer/transform_functions/eu_netherlands_transform_functions.py
Hi Plartoo
Could you please help me checking this new transform module?
=> Netherlands

data_architect_misc/data_transformer/configs/EU_Norway/config.json, data_architect_misc/data_transformer/transform_functions/eu_norway_transform_functions.py
Hi Plartoo
Could you please help me checking this new transform module?
=> New transform module for Norway data

data_architect_misc/data_transformer/transform_functions/eu_netherlands_transform_functions.py, data_architect_misc/data_transformer/transform_functions/eu_norway_transform_functions.py
Hi Don Plartoo
Could yuo please validate this new implementation such as Netherlands and as Norway?
=> Implemented a much better way to merge the sheets 

data_architect_misc/data_transformer/configs/EU_Poland/config.json, data_architect_misc/data_transformer/transform_functions/eu_poland_transform_functions.py
Hi Plartoo
Could you please validate these comments?
=> Poland updated

data_architect_misc/data_transformer/configs/AED_South_Africa/config.json
Hi Phyo, 
Please review and accept the pull request.
=> First commit from Yessica's computer.

data_architect_misc/data_transformer/transform_functions/common_transform_functions.py
Please Don plartoo could you please accept my change
Thank you
=> Drop rows function

data_architect_misc/data_transformer/configs/AED_GCC/config.json, data_architect_misc/data_transformer/configs/AED_Kenya/config.json, data_architect_misc/data_transformer/configs/AED_Morocco/config.json, data_architect_misc/data_transformer/configs/AED_Russia/config.json, data_architect_misc/data_transformer/configs/AED_South_Africa/config.json, data_architect_misc/data_transformer/configs/AED_Turkey/config.json, data_architect_misc/data_transformer/configs/AED_Ukraine/config.json, data_architect_misc/data_transformer/configs/APAC_Hong_Kong/step1_transform_raw_investment_data.json, data_architect_misc/data_transformer/configs/APAC_Hong_Kong/step2_combine_transformed_noncompete_and_compete_data.json, data_architect_misc/data_transformer/configs/APAC_India/config.json, data_architect_misc/data_transformer/configs/APAC_Malaysia/step1_transform_raw_investment_data.json, data_architect_misc/data_transformer/configs/APAC_Malaysia/step2_transform_sos_raw_investment_data.json, data_architect_misc/data_transformer/configs/APAC_Malaysia/step3_combine_tranformed_noncompete_and_compete_data.json, data_architect_misc/data_transformer/configs/APAC_Philippines/step1_transform_raw_investment_data.json, data_architect_misc/data_transformer/configs/APAC_Philippines/step2_combine_tranformed_noncompete_and_compete_data.json, data_architect_misc/data_transformer/configs/APAC_Singapore/config.json, data_architect_misc/data_transformer/configs/APAC_Taiwan/step1_transform_raw_investment_data.json, data_architect_misc/data_transformer/configs/APAC_Taiwan/step2_transform_sos_raw_investment_data.json, data_architect_misc/data_transformer/configs/APAC_Taiwan/step3_combine_tranformed_noncompete_and_compete_data.json, data_architect_misc/data_transformer/configs/APAC_Thailand/step1_transform_raw_investment_data.json, data_architect_misc/data_transformer/configs/APAC_Thailand/step2_transform_sos_raw_investment_data.json, data_architect_misc/data_transformer/configs/APAC_Thailand/step3_combine_tranformed_noncompete_and_compete_data.json, data_architect_misc/data_transformer/configs/APAC_Vietnam/step1_transform_raw_sos_investment_data.json, data_architect_misc/data_transformer/configs/APAC_Vietnam/step2_combine_tranformed_noncompete_and_trp_data.json, data_architect_misc/data_transformer/configs/_QA/common_comp_harm_post_transform_qa_config.json
Hi Plartoo
Could you please accept all these changes, I cannot sleep until these config files are up to date?
Thank you so much
=> New reviewing done
